### ISSUE TITLE
Field having no default

### ISSUE THREAD

**Issue by dhanikms** [sisl/AutonomousMerging.jl#5]
while running test_training.jl, this come up

Field 'exploration_policy' has no default, supply it with keyword.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] top-level scope at In[4]:32

**Comment by MaximeBouton** [comment]
oh there has been a new version of DeepQLearning.jl and I forgot to update the compat. 
You should use DeepQLearning.jl v0.4.x

**Comment by MaximeBouton** [comment]
3fa2bc2
